// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Earnings
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject earningsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Earnings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Year("Year"),
		Q1("Q1"),
		Q2("Q2"),
		Q3("Q3"),
		Q4("Q4");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Earnings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Earnings"));
	}

	protected Earnings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject earningsMendixObject)
	{
		if (earningsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Earnings", earningsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Earnings");

		this.earningsMendixObject = earningsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Earnings.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Earnings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Earnings.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Earnings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Earnings(context, mendixObject);
	}

	public static myfirstmodule.proxies.Earnings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Earnings.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Earnings> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Earnings> result = new java.util.ArrayList<myfirstmodule.proxies.Earnings>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Earnings" + xpathConstraint))
			result.add(myfirstmodule.proxies.Earnings.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Year
	 */
	public final java.lang.Integer getYear()
	{
		return getYear(getContext());
	}

	/**
	 * @param context
	 * @return value of Year
	 */
	public final java.lang.Integer getYear(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Year.toString());
	}

	/**
	 * Set value of Year
	 * @param year
	 */
	public final void setYear(java.lang.Integer year)
	{
		setYear(getContext(), year);
	}

	/**
	 * Set value of Year
	 * @param context
	 * @param year
	 */
	public final void setYear(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer year)
	{
		getMendixObject().setValue(context, MemberNames.Year.toString(), year);
	}

	/**
	 * @return value of Q1
	 */
	public final java.lang.Integer getQ1()
	{
		return getQ1(getContext());
	}

	/**
	 * @param context
	 * @return value of Q1
	 */
	public final java.lang.Integer getQ1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Q1.toString());
	}

	/**
	 * Set value of Q1
	 * @param q1
	 */
	public final void setQ1(java.lang.Integer q1)
	{
		setQ1(getContext(), q1);
	}

	/**
	 * Set value of Q1
	 * @param context
	 * @param q1
	 */
	public final void setQ1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer q1)
	{
		getMendixObject().setValue(context, MemberNames.Q1.toString(), q1);
	}

	/**
	 * @return value of Q2
	 */
	public final java.lang.Integer getQ2()
	{
		return getQ2(getContext());
	}

	/**
	 * @param context
	 * @return value of Q2
	 */
	public final java.lang.Integer getQ2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Q2.toString());
	}

	/**
	 * Set value of Q2
	 * @param q2
	 */
	public final void setQ2(java.lang.Integer q2)
	{
		setQ2(getContext(), q2);
	}

	/**
	 * Set value of Q2
	 * @param context
	 * @param q2
	 */
	public final void setQ2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer q2)
	{
		getMendixObject().setValue(context, MemberNames.Q2.toString(), q2);
	}

	/**
	 * @return value of Q3
	 */
	public final java.lang.Integer getQ3()
	{
		return getQ3(getContext());
	}

	/**
	 * @param context
	 * @return value of Q3
	 */
	public final java.lang.Integer getQ3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Q3.toString());
	}

	/**
	 * Set value of Q3
	 * @param q3
	 */
	public final void setQ3(java.lang.Integer q3)
	{
		setQ3(getContext(), q3);
	}

	/**
	 * Set value of Q3
	 * @param context
	 * @param q3
	 */
	public final void setQ3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer q3)
	{
		getMendixObject().setValue(context, MemberNames.Q3.toString(), q3);
	}

	/**
	 * @return value of Q4
	 */
	public final java.lang.Integer getQ4()
	{
		return getQ4(getContext());
	}

	/**
	 * @param context
	 * @return value of Q4
	 */
	public final java.lang.Integer getQ4(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Q4.toString());
	}

	/**
	 * Set value of Q4
	 * @param q4
	 */
	public final void setQ4(java.lang.Integer q4)
	{
		setQ4(getContext(), q4);
	}

	/**
	 * Set value of Q4
	 * @param context
	 * @param q4
	 */
	public final void setQ4(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer q4)
	{
		getMendixObject().setValue(context, MemberNames.Q4.toString(), q4);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return earningsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Earnings that = (myfirstmodule.proxies.Earnings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Earnings";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
