// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class ObjectWithData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject objectWithDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.ObjectWithData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Year("Year"),
		d1("d1"),
		d2("d2"),
		d3("d3"),
		d4("d4"),
		d5("d5");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ObjectWithData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.ObjectWithData"));
	}

	protected ObjectWithData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject objectWithDataMendixObject)
	{
		if (objectWithDataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.ObjectWithData", objectWithDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.ObjectWithData");

		this.objectWithDataMendixObject = objectWithDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ObjectWithData.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.ObjectWithData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.ObjectWithData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.ObjectWithData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.ObjectWithData(context, mendixObject);
	}

	public static myfirstmodule.proxies.ObjectWithData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.ObjectWithData.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Year
	 */
	public final java.lang.Integer getYear()
	{
		return getYear(getContext());
	}

	/**
	 * @param context
	 * @return value of Year
	 */
	public final java.lang.Integer getYear(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Year.toString());
	}

	/**
	 * Set value of Year
	 * @param year
	 */
	public final void setYear(java.lang.Integer year)
	{
		setYear(getContext(), year);
	}

	/**
	 * Set value of Year
	 * @param context
	 * @param year
	 */
	public final void setYear(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer year)
	{
		getMendixObject().setValue(context, MemberNames.Year.toString(), year);
	}

	/**
	 * @return value of d1
	 */
	public final java.lang.Integer getd1()
	{
		return getd1(getContext());
	}

	/**
	 * @param context
	 * @return value of d1
	 */
	public final java.lang.Integer getd1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.d1.toString());
	}

	/**
	 * Set value of d1
	 * @param d1
	 */
	public final void setd1(java.lang.Integer d1)
	{
		setd1(getContext(), d1);
	}

	/**
	 * Set value of d1
	 * @param context
	 * @param d1
	 */
	public final void setd1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer d1)
	{
		getMendixObject().setValue(context, MemberNames.d1.toString(), d1);
	}

	/**
	 * @return value of d2
	 */
	public final java.lang.Integer getd2()
	{
		return getd2(getContext());
	}

	/**
	 * @param context
	 * @return value of d2
	 */
	public final java.lang.Integer getd2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.d2.toString());
	}

	/**
	 * Set value of d2
	 * @param d2
	 */
	public final void setd2(java.lang.Integer d2)
	{
		setd2(getContext(), d2);
	}

	/**
	 * Set value of d2
	 * @param context
	 * @param d2
	 */
	public final void setd2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer d2)
	{
		getMendixObject().setValue(context, MemberNames.d2.toString(), d2);
	}

	/**
	 * @return value of d3
	 */
	public final java.lang.Integer getd3()
	{
		return getd3(getContext());
	}

	/**
	 * @param context
	 * @return value of d3
	 */
	public final java.lang.Integer getd3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.d3.toString());
	}

	/**
	 * Set value of d3
	 * @param d3
	 */
	public final void setd3(java.lang.Integer d3)
	{
		setd3(getContext(), d3);
	}

	/**
	 * Set value of d3
	 * @param context
	 * @param d3
	 */
	public final void setd3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer d3)
	{
		getMendixObject().setValue(context, MemberNames.d3.toString(), d3);
	}

	/**
	 * @return value of d4
	 */
	public final java.lang.Integer getd4()
	{
		return getd4(getContext());
	}

	/**
	 * @param context
	 * @return value of d4
	 */
	public final java.lang.Integer getd4(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.d4.toString());
	}

	/**
	 * Set value of d4
	 * @param d4
	 */
	public final void setd4(java.lang.Integer d4)
	{
		setd4(getContext(), d4);
	}

	/**
	 * Set value of d4
	 * @param context
	 * @param d4
	 */
	public final void setd4(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer d4)
	{
		getMendixObject().setValue(context, MemberNames.d4.toString(), d4);
	}

	/**
	 * @return value of d5
	 */
	public final java.lang.Integer getd5()
	{
		return getd5(getContext());
	}

	/**
	 * @param context
	 * @return value of d5
	 */
	public final java.lang.Integer getd5(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.d5.toString());
	}

	/**
	 * Set value of d5
	 * @param d5
	 */
	public final void setd5(java.lang.Integer d5)
	{
		setd5(getContext(), d5);
	}

	/**
	 * Set value of d5
	 * @param context
	 * @param d5
	 */
	public final void setd5(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer d5)
	{
		getMendixObject().setValue(context, MemberNames.d5.toString(), d5);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return objectWithDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.ObjectWithData that = (myfirstmodule.proxies.ObjectWithData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.ObjectWithData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
